require: rubocop-performance

Metrics/LineLength:
  Max: 150
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/NumericLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Metrics/AbcSize:
  Max: 18
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 8
Style/GuardClause:
  Enabled: false
Naming/FileName:
  Enabled: false
