Metrix/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 120
Style/NumericLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/EmptyMethod:
  Enabled: false

