twitter_app: &twitter_app
  consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_app:
    <<: *twitter_app

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_app:
    <<: *twitter_app

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_app:
    <<: *twitter_app
